[profile.default]
optimizer = true
optimizer_runs = 44444444
via_ir = true
ffi = true
fs_permissions = [{ access = 'read-write', path = './'}]

additional_compiler_profiles = [
  { name = "si_router", via_ir = true, optimizer_runs = 1000 }
]

compilation_restrictions = [
  { paths = "src/KSSmartIntentRouter.sol", optimizer_runs = 1000 },
]

[fmt]
line_length = 100
tab_width = 2
quote_style = 'single'
number_underscore = 'thousands'
sort_imports = true

[fuzz]
runs = 20

[rpc_endpoints]
mainnet = "${ETH_NODE_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options