[profile.default]
optimizer = true
optimizer_runs = 200
via_ir = true
ffi = true
fs_permissions = [{ access = 'read-write', path = './'}]

[fmt]
line_length = 100
tab_width = 2
quote_style = 'single'
number_underscore = 'thousands'
sort_imports = true

[fuzz]
runs = 20

[rpc_endpoints]
mainnet = "${ETH_NODE_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options