name: Build page

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: KyberNetwork/workflows-templates/.github/workflows/build-image-v0.1.1.yml@main
    with:
      IMAGE_REPOSITORY: asia.gcr.io/kyber-operation/sc/smart-intent-doc
      DOCKERFILE_PATH: ./Dockerfile
      DOCKER_CONTEXT: ./
    secrets:
      GCR_CREDENTIALS: ${{ secrets.GCR_CREDENTIALS }}
