name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  ETH_NODE_URL: ${{ secrets.ETH_NODE_URL }}
  BSC_NODE_URL: ${{ secrets.BSC_NODE_URL }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: KyberNetwork/foundry-toolchain@master
        with:
          version: v1.4.2

      - name: Build
        run: |
          forge --version
          forge build --sizes --skip Mock Utils test
        id: build

      - name: Run tests
        run: forge test --nmt testMockActionExecuteSuccessP256 --isolate
        id: test
      
      - name: Run tests P256
        run: forge test --mt testMockActionExecuteSuccessP256 --evm-version osaka --isolate